function generate_dspace_wrapper()
    % Create a wrapper file that dSpace/Simulink can call more easily
    
    wrapper_code = [...
        '#include "nlp_solver.h"\n' ...
        '#include <stddef.h>\n\n' ...
        
        '/* Persistent state for warm start */\n' ...
        'static double lam_x0[2] = {0.0, 0.0};\n' ...
        'static double lam_g0[6] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0};\n' ...
        'static double x_prev[2] = {5.0, 0.1};  /* Initial guess */\n\n' ...
        
        '/* dSpace-friendly wrapper function */\n' ...
        'int solve_nlp_realtime(double wind_speed, double* rotor_speed, double* pitch_angle)\n' ...
        '{\n' ...
        '    /* Set up problem inputs */\n' ...
        '    double p[1] = {wind_speed};  /* wind speed parameter */\n' ...
        '    double x0[2] = {x_prev[0], x_prev[1]};  /* warm start from previous */\n' ...
        '    double x_sol[2];\n' ...
        '    double g_sol[6];  /* 6 constraints */\n' ...
        '    double ubx[2] = {15.0, 1.57};  /* Upper bounds: rotor speed, pitch */\n' ...
        '    double lbx[2] = {0.5, -0.1};   /* Lower bounds: rotor speed, pitch */\n' ...
        '    double ubg[6] = {INFINITY, 1500.0, INFINITY, INFINITY, 4000.0, INFINITY};\n' ...
        '    double lbg[6] = {0.0, -INFINITY, -INFINITY, -INFINITY, 0.0, -INFINITY};\n\n' ...
        
        '    /* Create solver instance */\n' ...
        '    void* solver = F_new();\n' ...
        '    if (solver == NULL) return -1;\n\n' ...
        
        '    /* Call solver */\n' ...
        '    int flag = F(solver, x0, p, NULL, x_sol, g_sol, NULL, NULL, lam_g0, lam_x0);\n\n' ...
        
        '    /* Check solver status */\n' ...
        '    if (flag == 0) {\n' ...
        '        *rotor_speed = x_sol[0];\n' ...
        '        *pitch_angle = x_sol[1];\n' ...
        '        x_prev[0] = x_sol[0];  /* Store for next iteration */\n' ...
        '        x_prev[1] = x_sol[1];\n' ...
        '        return 1;  /* Success */\n' ...
        '    } else {\n' ...
        '        /* Solver failed, use previous solution */\n' ...
        '        *rotor_speed = x_prev[0];\n' ...
        '        *pitch_angle = x_prev[1];\n' ...
        '        return 0;  /* Fallback */\n' ...
        '    }\n' ...
        '    F_free(solver);\n' ...
        '}\n' ...
    ];
    
    fid = fopen('nlp_solver_dspace_wrapper.c', 'w');
    fprintf(fid, wrapper_code);
    fclose(fid);
    
    disp('gemaakt nlp_solver_dspace_wrapper.c');
    
end
