/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int F(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int F_alloc_mem(void);
int F_init_mem(int mem);
void F_free_mem(int mem);
int F_checkout(void);
void F_release(int mem);
void F_incref(void);
void F_decref(void);
casadi_int F_n_in(void);
casadi_int F_n_out(void);
casadi_real F_default_in(casadi_int i);
const char* F_name_in(casadi_int i);
const char* F_name_out(casadi_int i);
const casadi_int* F_sparsity_in(casadi_int i);
const casadi_int* F_sparsity_out(casadi_int i);
int F_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int F_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define F_SZ_ARG 22
#define F_SZ_RES 15
#define F_SZ_IW 14
#define F_SZ_W 156
#ifdef __cplusplus
} /* extern "C" */
#endif
